/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayeventsRouteImport } from './routes/playevents'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizadoresIndexRouteImport } from './routes/organizadores/index'
import { Route as PlayeventsEventIdRouteImport } from './routes/playevents/$eventId'
import { Route as PatrocinadoresRoiRouteImport } from './routes/patrocinadores_.roi'
import { Route as PatrocinadoresRankingRouteImport } from './routes/patrocinadores_.ranking'
import { Route as PatrocinadoresEventosRouteImport } from './routes/patrocinadores_.eventos'
import { Route as PatrocinadoresCalendarioRouteImport } from './routes/patrocinadores_.calendario'
import { Route as OrganizadoresRelatoriosRouteImport } from './routes/organizadores/relatorios'
import { Route as OrganizadoresRankingRouteImport } from './routes/organizadores/ranking'
import { Route as OrganizadoresPatrocinadoresRouteImport } from './routes/organizadores/patrocinadores'
import { Route as OrganizadoresEventosRouteImport } from './routes/organizadores/eventos'

const PlayeventsRoute = PlayeventsRouteImport.update({
  id: '/playevents',
  path: '/playevents',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadoresIndexRoute = OrganizadoresIndexRouteImport.update({
  id: '/organizadores/',
  path: '/organizadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayeventsEventIdRoute = PlayeventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => PlayeventsRoute,
} as any)
const PatrocinadoresRoiRoute = PatrocinadoresRoiRouteImport.update({
  id: '/patrocinadores_/roi',
  path: '/patrocinadores/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRankingRoute = PatrocinadoresRankingRouteImport.update({
  id: '/patrocinadores_/ranking',
  path: '/patrocinadores/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresEventosRoute = PatrocinadoresEventosRouteImport.update({
  id: '/patrocinadores_/eventos',
  path: '/patrocinadores/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresCalendarioRoute =
  PatrocinadoresCalendarioRouteImport.update({
    id: '/patrocinadores_/calendario',
    path: '/patrocinadores/calendario',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizadoresRelatoriosRoute = OrganizadoresRelatoriosRouteImport.update({
  id: '/organizadores/relatorios',
  path: '/organizadores/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadoresRankingRoute = OrganizadoresRankingRouteImport.update({
  id: '/organizadores/ranking',
  path: '/organizadores/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadoresPatrocinadoresRoute =
  OrganizadoresPatrocinadoresRouteImport.update({
    id: '/organizadores/patrocinadores',
    path: '/organizadores/patrocinadores',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizadoresEventosRoute = OrganizadoresEventosRouteImport.update({
  id: '/organizadores/eventos',
  path: '/organizadores/eventos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/perfil': typeof PerfilRoute
  '/playevents': typeof PlayeventsRouteWithChildren
  '/organizadores/eventos': typeof OrganizadoresEventosRoute
  '/organizadores/patrocinadores': typeof OrganizadoresPatrocinadoresRoute
  '/organizadores/ranking': typeof OrganizadoresRankingRoute
  '/organizadores/relatorios': typeof OrganizadoresRelatoriosRoute
  '/patrocinadores/calendario': typeof PatrocinadoresCalendarioRoute
  '/patrocinadores/eventos': typeof PatrocinadoresEventosRoute
  '/patrocinadores/ranking': typeof PatrocinadoresRankingRoute
  '/patrocinadores/roi': typeof PatrocinadoresRoiRoute
  '/playevents/$eventId': typeof PlayeventsEventIdRoute
  '/organizadores/': typeof OrganizadoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/perfil': typeof PerfilRoute
  '/playevents': typeof PlayeventsRouteWithChildren
  '/organizadores/eventos': typeof OrganizadoresEventosRoute
  '/organizadores/patrocinadores': typeof OrganizadoresPatrocinadoresRoute
  '/organizadores/ranking': typeof OrganizadoresRankingRoute
  '/organizadores/relatorios': typeof OrganizadoresRelatoriosRoute
  '/patrocinadores/calendario': typeof PatrocinadoresCalendarioRoute
  '/patrocinadores/eventos': typeof PatrocinadoresEventosRoute
  '/patrocinadores/ranking': typeof PatrocinadoresRankingRoute
  '/patrocinadores/roi': typeof PatrocinadoresRoiRoute
  '/playevents/$eventId': typeof PlayeventsEventIdRoute
  '/organizadores': typeof OrganizadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/perfil': typeof PerfilRoute
  '/playevents': typeof PlayeventsRouteWithChildren
  '/organizadores/eventos': typeof OrganizadoresEventosRoute
  '/organizadores/patrocinadores': typeof OrganizadoresPatrocinadoresRoute
  '/organizadores/ranking': typeof OrganizadoresRankingRoute
  '/organizadores/relatorios': typeof OrganizadoresRelatoriosRoute
  '/patrocinadores_/calendario': typeof PatrocinadoresCalendarioRoute
  '/patrocinadores_/eventos': typeof PatrocinadoresEventosRoute
  '/patrocinadores_/ranking': typeof PatrocinadoresRankingRoute
  '/patrocinadores_/roi': typeof PatrocinadoresRoiRoute
  '/playevents/$eventId': typeof PlayeventsEventIdRoute
  '/organizadores/': typeof OrganizadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patrocinadores'
    | '/perfil'
    | '/playevents'
    | '/organizadores/eventos'
    | '/organizadores/patrocinadores'
    | '/organizadores/ranking'
    | '/organizadores/relatorios'
    | '/patrocinadores/calendario'
    | '/patrocinadores/eventos'
    | '/patrocinadores/ranking'
    | '/patrocinadores/roi'
    | '/playevents/$eventId'
    | '/organizadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patrocinadores'
    | '/perfil'
    | '/playevents'
    | '/organizadores/eventos'
    | '/organizadores/patrocinadores'
    | '/organizadores/ranking'
    | '/organizadores/relatorios'
    | '/patrocinadores/calendario'
    | '/patrocinadores/eventos'
    | '/patrocinadores/ranking'
    | '/patrocinadores/roi'
    | '/playevents/$eventId'
    | '/organizadores'
  id:
    | '__root__'
    | '/'
    | '/patrocinadores'
    | '/perfil'
    | '/playevents'
    | '/organizadores/eventos'
    | '/organizadores/patrocinadores'
    | '/organizadores/ranking'
    | '/organizadores/relatorios'
    | '/patrocinadores_/calendario'
    | '/patrocinadores_/eventos'
    | '/patrocinadores_/ranking'
    | '/patrocinadores_/roi'
    | '/playevents/$eventId'
    | '/organizadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  PerfilRoute: typeof PerfilRoute
  PlayeventsRoute: typeof PlayeventsRouteWithChildren
  OrganizadoresEventosRoute: typeof OrganizadoresEventosRoute
  OrganizadoresPatrocinadoresRoute: typeof OrganizadoresPatrocinadoresRoute
  OrganizadoresRankingRoute: typeof OrganizadoresRankingRoute
  OrganizadoresRelatoriosRoute: typeof OrganizadoresRelatoriosRoute
  PatrocinadoresCalendarioRoute: typeof PatrocinadoresCalendarioRoute
  PatrocinadoresEventosRoute: typeof PatrocinadoresEventosRoute
  PatrocinadoresRankingRoute: typeof PatrocinadoresRankingRoute
  PatrocinadoresRoiRoute: typeof PatrocinadoresRoiRoute
  OrganizadoresIndexRoute: typeof OrganizadoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playevents': {
      id: '/playevents'
      path: '/playevents'
      fullPath: '/playevents'
      preLoaderRoute: typeof PlayeventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores/': {
      id: '/organizadores/'
      path: '/organizadores'
      fullPath: '/organizadores/'
      preLoaderRoute: typeof OrganizadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playevents/$eventId': {
      id: '/playevents/$eventId'
      path: '/$eventId'
      fullPath: '/playevents/$eventId'
      preLoaderRoute: typeof PlayeventsEventIdRouteImport
      parentRoute: typeof PlayeventsRoute
    }
    '/patrocinadores_/roi': {
      id: '/patrocinadores_/roi'
      path: '/patrocinadores/roi'
      fullPath: '/patrocinadores/roi'
      preLoaderRoute: typeof PatrocinadoresRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores_/ranking': {
      id: '/patrocinadores_/ranking'
      path: '/patrocinadores/ranking'
      fullPath: '/patrocinadores/ranking'
      preLoaderRoute: typeof PatrocinadoresRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores_/eventos': {
      id: '/patrocinadores_/eventos'
      path: '/patrocinadores/eventos'
      fullPath: '/patrocinadores/eventos'
      preLoaderRoute: typeof PatrocinadoresEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores_/calendario': {
      id: '/patrocinadores_/calendario'
      path: '/patrocinadores/calendario'
      fullPath: '/patrocinadores/calendario'
      preLoaderRoute: typeof PatrocinadoresCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores/relatorios': {
      id: '/organizadores/relatorios'
      path: '/organizadores/relatorios'
      fullPath: '/organizadores/relatorios'
      preLoaderRoute: typeof OrganizadoresRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores/ranking': {
      id: '/organizadores/ranking'
      path: '/organizadores/ranking'
      fullPath: '/organizadores/ranking'
      preLoaderRoute: typeof OrganizadoresRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores/patrocinadores': {
      id: '/organizadores/patrocinadores'
      path: '/organizadores/patrocinadores'
      fullPath: '/organizadores/patrocinadores'
      preLoaderRoute: typeof OrganizadoresPatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores/eventos': {
      id: '/organizadores/eventos'
      path: '/organizadores/eventos'
      fullPath: '/organizadores/eventos'
      preLoaderRoute: typeof OrganizadoresEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlayeventsRouteChildren {
  PlayeventsEventIdRoute: typeof PlayeventsEventIdRoute
}

const PlayeventsRouteChildren: PlayeventsRouteChildren = {
  PlayeventsEventIdRoute: PlayeventsEventIdRoute,
}

const PlayeventsRouteWithChildren = PlayeventsRoute._addFileChildren(
  PlayeventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  PerfilRoute: PerfilRoute,
  PlayeventsRoute: PlayeventsRouteWithChildren,
  OrganizadoresEventosRoute: OrganizadoresEventosRoute,
  OrganizadoresPatrocinadoresRoute: OrganizadoresPatrocinadoresRoute,
  OrganizadoresRankingRoute: OrganizadoresRankingRoute,
  OrganizadoresRelatoriosRoute: OrganizadoresRelatoriosRoute,
  PatrocinadoresCalendarioRoute: PatrocinadoresCalendarioRoute,
  PatrocinadoresEventosRoute: PatrocinadoresEventosRoute,
  PatrocinadoresRankingRoute: PatrocinadoresRankingRoute,
  PatrocinadoresRoiRoute: PatrocinadoresRoiRoute,
  OrganizadoresIndexRoute: OrganizadoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
